import type { IconPack } from '@fortawesome/fontawesome-svg-core'

import {
  faCalendar,
  faCalendarDays,
  faCalendarCheck,
  faFolder,
  faCircleStop,
  faCircleXmark,
  faCircleRight,
  faCircleLeft,
  faFlag,
  faUser,
  faClock,
  faWindowRestore,
  faFileLines,
  faCopy,
  faHeart,
  faEye,
  faEyeSlash,
  faTrashCan,
  faStar,
  faSave,
  faFileExcel,
  faFilePdf,
  faFloppyDisk,
  faPaperPlane,
  faObjectGroup,
  faHardDrive,
  faFolderOpen,
  faFileVideo,
  faChartBar,
  faChessPawn,
  faFaceGrinHearts,
  faFaceLaughSquint,
  faHandPointLeft,
  faCopyright,
  faSquareCheck
} from '@fortawesome/free-regular-svg-icons'

const far: IconPack = {
  faCalendar,
  faCalendarDays,
  faCalendarCheck,
  faFolder,
  faCircleStop,
  faCircleXmark,
  faCircleRight,
  faCircleLeft,
  faFlag,
  faUser,
  faClock,
  faWindowRestore,
  faFileLines,
  faCopy,
  faHeart,
  faEye,
  faEyeSlash,
  faTrashCan,
  faStar,
  faSave,
  faFileExcel,
  faFilePdf,
  faFloppyDisk,
  faPaperPlane,
  faObjectGroup,
  faHardDrive,
  faFolderOpen,
  faFileVideo,
  faChartBar,
  faChessPawn,
  faFaceGrinHearts,
  faFaceLaughSquint,
  faHandPointLeft,
  faCopyright,
  faSquareCheck
}

export default far
