import {
  Question16Filled,
  Engine24Filled,
  GanttChart20Filled,
  BoxMultipleCheckmark20Filled,
  BoxCheckmark24Filled,
  ArrowSort28Filled,
  ClipboardArrowRight16Filled,
  EyeTracking16Filled,
  EyeTrackingOff16Filled,
  CalendarSearch20Filled,
  DualScreenClock24Filled,
  Table28Regular,
  TableFreezeColumn28Regular,
  DeviceMeetingRoomRemote16Filled,
  ClipboardTaskListLtr20Regular,
  ContentSettings24Regular,
  BoxDismiss24Regular,
  BoxCheckmark24Regular,
  DocumentBulletListClock20Regular,
  CalendarArrowRight20Filled,
  DesktopArrowRight24Regular,
  SlideArrowRight24Regular,
  ClipboardArrowRight16Regular,
  BookQuestionMark24Filled,
  DocumentTableCube20Filled
} from '@vicons/fluent'

const fluent: Record<string, any> = {
  Question16Filled,
  Engine24Filled,
  GanttChart20Filled,
  BoxMultipleCheckmark20Filled,
  BoxCheckmark24Filled,
  ArrowSort28Filled,
  ClipboardArrowRight16Filled,
  EyeTracking16Filled,
  EyeTrackingOff16Filled,
  CalendarSearch20Filled,
  DualScreenClock24Filled,
  Table28Regular,
  TableFreezeColumn28Regular,
  DeviceMeetingRoomRemote16Filled,
  ClipboardTaskListLtr20Regular,
  ContentSettings24Regular,
  BoxDismiss24Regular,
  BoxCheckmark24Regular,
  DocumentBulletListClock20Regular,
  CalendarArrowRight20Filled,
  DesktopArrowRight24Regular,
  SlideArrowRight24Regular,
  ClipboardArrowRight16Regular,
  BookQuestionMark24Filled,
  DocumentTableCube20Filled
}

export default fluent
